### (API 1)

GET http://localhost:3003/states/

### (API 2) 

GET http://localhost:3003/states/5/

### (API 3)
POST http://localhost/3003/districts/
Content-Type: application/json 

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

### (API 4

GET http://localhost:3003/districts/5/

### 
DELETE http://localhost:3003/districts/8/

### 
PUT http://localhost:3003/districts/322/
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}